spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/mymedical
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh